export const componentCategories = [
  "Processors (CPUs)",
  "Motherboards",
  "Graphics Cards (GPUs)",
  "RAM (Memory)",
  "Storage",
  "Power Supplies (PSUs)",
  "Computer Cases",
  "Cooling Solutions",
  "Operating Systems",
  "Accessories",
  "Cables and Adapters",
  "Customization and Aesthetics",
  "Build Kits",
  "Compatibility Guides",
  "User Reviews and Ratings",
];
